<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RootNamespace>CodeJanitor.Web.API</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MediatR" Version="13.0.0"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CodeJanitor.Docker.Application\CodeJanitor.Docker.Application.csproj"/>
        <ProjectReference Include="..\CodeJanitor.Platform.Application\CodeJanitor.Platform.Application.csproj"/>
        <ProjectReference Include="..\CodeJanitor.Platform.GitLab.Infrastructure\CodeJanitor.Platform.GitLab.Infrastructure.csproj"/>
    </ItemGroup>

</Project>
