<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="MediatR">
            <HintPath>..\..\..\.nuget\packages\mediatr\13.0.0\lib\net9.0\MediatR.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CodeJanitor.Shared.Domain\CodeJanitor.Shared.Domain.csproj"/>
    </ItemGroup>

</Project>
